added hand joint state publisher
squirrel-project/squirrel_robotino pull request #180
Opened 2017-02-14 10:51 UTC by mzillich

2017-02-14 10:51 UTC, mzillich commented
Hi @ipa-nhg , not sure if the robotino.urdf here is correct. It has base_linkz.

2017-02-14 11:21 UTC, ipa-nhg requested changes

2017-02-14 11:21 UTC, ipa-nhg commented on robotino_bringup/robots/tuw-robotino2/urdf/robotino.urdf
> +    <parent link="base_link"/>
I think this is wrong... the robotino.urdf is the file used by moveit!, doesn't it?

2017-02-24 08:46 UTC, ipa-nhg approved these changes

2017-02-24 08:46 UTC, merged